image:
- Visual Studio 2022
- Ubuntu2004

for:
  - matrix:
      only:
        - image: Visual Studio 2022
    cache:
      - '%USERPROFILE%\.m2 -> **\pom.xml'
  - matrix:
      only:
        - image: Ubuntu2004
    cache:
      - '$HOME/.m2 -> **/pom.xml'

build_script:
  - mvn package

artifacts:
  - path: 'target\*.jar'
